export default {
  PICK_TILE: 'PICK_TILE',
  SET_BOARD: 'SET_BOARD',
  TOGGLE_ACTIVE_PLAYER: 'TOGGLE_ACTIVE_PLAYER',
  SET_GAMESTATE_TO_WIN: 'SET_GAMESTATE_TO_WIN',
  SET_GAMESTATE: 'SET_GAMESTATE'
}
